name: Update ADK LLMs List

on:
  schedule:
    # Run every 24 hours
    - cron: '0 */24 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: List files in the repository
      run: ls -R

    - name: Fetch latest LLMs list
      run: python scripts/fetch_llms_list.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/
        # This command checks for changes and only commits & pushes if there are any.
        git diff --cached --quiet || (git commit -m "Update llms-full.txt from google/adk-python" && git push)
